/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import edu.princeton.cs.algs4.Draw;

import javax.swing.*;
import java.awt.*;

public class App {
    Draw draw;

    public App(){
        this.draw = new Draw();
        this.draw.setCanvasSize(1600, 900);
        this.draw.setXscale(0, 1600);
        this.draw.setYscale(0, 900);
        this.draw.setPenColor(0, 0, 20);
        this.draw.filledRectangle(800, 450, 800, 450);
        draw.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }
    public static void main(String[] args) {
        App app = new App();
        Sistema_solar solar = new Sistema_solar();

        Planeta terra = new Planeta(3, 10, Color.BLUE);
        solar.add_planeta(terra);

        solar.desenha(app.draw);
    }
}