/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import edu.princeton.cs.algs4.Draw;

import javax.swing.*;
import java.awt.*;

public class App {
    Draw draw;

    public App(){
        this.draw = new Draw();
        this.draw.setCanvasSize(1600, 900);
        this.draw.setXscale(0, 1600);
        this.draw.setYscale(0, 900);
        this.draw.setPenColor(0, 0, 20);
        this.draw.filledRectangle(800, 450, 800, 450);
        draw.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }
    public static void main(String[] args) throws InterruptedException{
        App app = new App();
        Sistema_solar solar = new Sistema_solar(8);

        Planeta terra = new Planeta(3, 9, 16, false, new Color(0, 150, 200));
        solar.add_planeta(terra);

        Planeta netuno = new Planeta(8, 20, 1, false, new Color(0, 0, 100));
        solar.add_planeta(netuno);

        Planeta jupiter = new Planeta(5, 20, 6, false, new Color(255, 200, 100));
        solar.add_planeta(jupiter);

        Planeta marte = new Planeta(4, 7, 8, false, new Color(153, 0, 0));
        solar.add_planeta(marte);

        Planeta urano = new Planeta(7, 12, 2, false, Color.CYAN);
        solar.add_planeta(urano);

        Planeta mercurio = new Planeta(1, 4, 22, false, new Color(140,  70, 20));
        solar.add_planeta(mercurio);

        Planeta venus = new Planeta(2, 5, 12, false, new Color(255, 140, 50));
        solar.add_planeta(venus);

        Planeta saturno = new Planeta(6, 16, 4, true, new Color(210, 180, 90));
        solar.add_planeta(saturno);

        double angulo = 0;
        app.draw.enableDoubleBuffering();

        while (true) {
            solar.desenha(app.draw); // redesenha sol e órbitas (como se "limpasse" tudo)
            solar.desenha_planeta(app.draw, angulo); // Desenha um ponto por planeta

            angulo += 0.02;
            if (angulo > 2 * Math.PI)
                angulo = 0;

            app.draw.show();
            Thread.sleep(100); //
        }
    }
}